spring.application.name=SpringBootCallingThirdPartyAPI

server.port=8081

currency.key="x-rapidapi-key"
currency.value="650b8aea0cmshc580a2cefb4df87p172f51js"
company.key="x-rapidapi-key"
company.value="650b8aea0cmshc580a2cefb4df87p172f51js"

